---
default:
  generator: rrdn_adv
  feature_extractor: True
  discriminator: True
  training_set: div2k
  test_set: sample
log_dirs:
  logs: ./logs
  weights: ./weights
feature_extractor:
  vgg19_adv:
    layers_to_extract:
      - 5
      - 9
generators:
  rrdn_adv:
    C: 4
    D: 3
    G: 64
    G0: 64
    T: 10
    x: scale
loss_weights:
  generator:0.06
  feature_extractor: 0.0833
  discriminator: 0.04
losses:
  generator: mae
  discriminator: binary_crossentropy
  feature_extractor: mse
session:
  prediction:
    patch_size:
  training:
    epochs: 120
    steps_per_epoch: 500
    batch_size: 2
    monitored_metrics={'val_generator_PSNR_Y': 'max'}
    learning_rate:
      initial_value: 0.0004
      decay_frequency: 50
      decay_factor: 0.5
    fallback_save_every_n_epochs: 2
    flatness:
      min: 0.0
      increase_frequency: null
      increase: 0.0
      max: 0.0
    metrics:
      generator: PSNR_Y
    monitored_metrics:
      val_loss: min
      val_PSNR_Y: max
    adam_optimizer:
      beta1: 0.9
      beta2: 0.999
      epsilon: null
test_sets:
  sample: ./sample
training_sets:
  pathology images_data:
    lr_train_dir: ./data/lr128_data
    hr_train_dir: ['/data/hr256_data','/data/hr512_data','/data/hr1024_data']
    lr_valid_dir: ./data/lr128_val
    hr_valid_dir: ['/data/hr256_val','/data/hr512_val','/data/hr1024_val']
    data_name: data
  div2k:
    lr_train_dir: ./data/DIV2K/DIV2K_train_LR_bicubic/X2
    hr_train_dir: ./data/DIV2K/DIV2K_train_HR
    lr_valid_dir: ./data/DIV2K/DIV2K_valid_LR_bicubic/X2
    hr_valid_dir: ./data/DIV2K/DIV2K_valid_HR
    data_name: div2k
weights_paths:
  discriminator:
  generator:
